#! /bin/sh

LOOKBACK_HOURS="${1:-1}"
VIRUS_ACTION="${2:-QUARANTINE}"

echo "run invoke_jobs.py SCAN_VIRUS with VIRUS_SCAN_LOOKBACK_HOURS=${LOOKBACK_HOURS} VIRUS_SCAN_ACTION=${VIRUS_ACTION}"
VIRUS_SCAN_LOOKBACK_HOURS="${LOOKBACK_HOURS}" VIRUS_SCAN_ACTION="${VIRUS_ACTION}" python3 invoke_jobs.py SCAN_VIRUS
